backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Sub Title, name: subtitle, widget: string }
          - { label: Summary, name: summary, widget: string }
          - { label: 'About Body', name: 'body', widget: 'markdown' }
          - { label: 'Services', name: 'services', widget: 'list' }
          - {
              label: Portfolio,
              name: offerings,
              widget: object,
              fields:
                [
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                        { label: Video ID, name: video, widget: number },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: 'Meta Title', name: 'meta_title', widget: 'string' }
          - {
              label: 'Meta Description',
              name: 'meta_description',
              widget: 'text',
            }
      - file: 'src/pages/contact/index.md'
        label: 'Contact Page'
        name: 'contact'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'contact-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: 'Meta Title', name: 'meta_title', widget: 'string' }
          - {
              label: 'Meta Description',
              name: 'meta_description',
              widget: 'text',
            }
          - { label: 'Services', name: 'services', widget: 'list' }
    - name: 'blog'
      label: 'Blog'
      folder: 'src/pages/blog'
      create: true
      slug: '{{slug}}'
      fields:
        - {
            label: 'Template Key',
            name: 'templateKey',
            widget: 'hidden',
            default: 'article-page',
          }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Slug', name: 'slug', widget: 'string' }
        - { label: 'Publish Date', name: 'date', widget: 'datetime' }
        - { label: 'Cover', name: 'cover', widget: 'image' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - { label: 'Tags', name: 'tags', widget: 'list' }
        - { label: 'Meta Title', name: 'meta_title', widget: 'string' }
        - { label: 'Meta Description', name: 'meta_description', widget: 'text' }
